// <auto-generated />
using System;
using CourseLibrary.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(BeerLibraryContext))]
    [Migration("20210622075320_MakeIdAutoincMigration")]
    partial class MakeIdAutoincMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseLibrary.API.Entities.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BeerRating")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("BeerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8c210b9-6562-4b7d-9543-351e3afb813b"),
                            BeerName = "Berry",
                            BeerRating = 1,
                            BeerType = "Griffin Beak Eldritch"
                        },
                        new
                        {
                            Id = new Guid("3e784ca5-9639-423d-8a22-7cb2c41f3142"),
                            BeerName = "Nancy",
                            BeerRating = 2,
                            BeerType = "Swashbuckler Rye"
                        },
                        new
                        {
                            Id = new Guid("cc65d2ae-e39c-4744-9157-7b530635a403"),
                            BeerName = "Eli",
                            BeerRating = 3,
                            BeerType = "Ivory Bones Sweet"
                        },
                        new
                        {
                            Id = new Guid("66b59e1f-adf4-4044-b546-1c438e1fa951"),
                            BeerName = "Arnold",
                            BeerRating = 4,
                            BeerType = "The Unseen Stafford"
                        },
                        new
                        {
                            Id = new Guid("600ad036-1305-4460-99db-9f54112f1178"),
                            BeerName = "Seabury",
                            BeerRating = 5,
                            BeerType = "Toxic Reyson"
                        },
                        new
                        {
                            Id = new Guid("d22649ce-d557-4e06-a781-f5801683c7a2"),
                            BeerName = "Rutherford",
                            BeerRating = 4,
                            BeerType = "Fearless Cloven"
                        },
                        new
                        {
                            Id = new Guid("af83e446-83b7-430a-bc47-df675bd702bd"),
                            BeerName = "Atherton",
                            BeerRating = 2,
                            BeerType = "Crow Ridley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
